jeu:  main.c check_line.c ft_isdigit.c parse_map.c parse_rgb.c parse_tex.c screen.c valid_map.c color.c image.c parse.c ../gnl/get_next_line.c ../gnl/get_next_line_utils.c
	clang main.c check_line.c ft_isdigit.c parse_map.c parse_rgb.c parse_tex.c screen.c valid_map.c color.c image.c parse.c ../gnl/get_next_line.c ../gnl/get_next_line_utils.c ../minilibx-linux/libmlx_Linux.a -lXext -lX11 -lm
